#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-0_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-1_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-2_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-3_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-4_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-5_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-6_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-7_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-8_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
#./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-9_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-10_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-11_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-12_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-13_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-14_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-15_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-16_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-17_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-18_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-19_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-20_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-21_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-22_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-23_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-24_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-25_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-26_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-27_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-28_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-29_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-30_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-31_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-32_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-33_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-34_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-35_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-36_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-37_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-38_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-39_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-40_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-41_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-42_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-43_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-44_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-45_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-46_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-47_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-48_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-49_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-50_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-51_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-52_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-53_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-54_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-55_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-56_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-57_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-58_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-59_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-60_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-61_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-62_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-63_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-64_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-65_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-66_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-67_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-68_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-69_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-70_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-71_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-72_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-73_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-74_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-75_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-76_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-77_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-78_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-79_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-80_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-81_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-82_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-83_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-84_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-85_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-86_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-87_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-88_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-89_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-90_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-91_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-92_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-93_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-94_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-95_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-96_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-97_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-98_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-99_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt  -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-100_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-101_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-102_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-103_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-104_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-105_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-106_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-107_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-108_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-109_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-110_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-111_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-112_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-113_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-114_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-115_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-116_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-117_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-118_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-119_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-120_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-121_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-122_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-123_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-124_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-125_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-126_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-127_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-128_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-129_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-130_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-131_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-132_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-133_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-134_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-135_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-136_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-137_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-138_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-139_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-140_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-141_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-142_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-143_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-144_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-145_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-146_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-147_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-148_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-149_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-150_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-151_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-152_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-153_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-154_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-155_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-156_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
./tracker_seek -f /home/wangying/desktop/muon_soft/data/07241638/dec_out/unpack_result/dec_result/muon-157_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt -j -T
