./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-0_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-1_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-2_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-3_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-4_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-5_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-6_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-7_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-8_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-9_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-10_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-11_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-12_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-13_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-14_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-15_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-16_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-17_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-18_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-19_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-20_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-21_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
./tracker_seek -f /home/wangying/desktop/150_multiLayerTst/08090929/dec_out/unpack_result/dec_result/muon-22_dec_mt_hit_data_link0x3F.root -L 5 -D 6 -l 0x3F -r offset_initial.txt   -j -T
